In [3]:
import numpy as np
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)
print(type(ar))
data = [0,1,2,3,4,5,6,7,8,9]
print(type(data))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'list'>


In [4]:
#for 반복문을 이용하면 다음과 같이 구현할 수 있다
answer = []
for di in data:
  answer.append(2*di)
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [6]:
#array는 numpy에 있는 배열로 import numpy를 한 다음에 쓸 수 있다
#리스트보다 구동 시간과 용량이 작으며 동일한 문자형(int같은거)만 사용 가능하다
x = np.array(data)
print(x)

#array는 벡터연산으로 배열에 2를 곱하면 각 요소에 2를 곱한 값이 나오지만
print(2*x)

#리스트는 2를 곱하면 자료가 2배로 는다
L = [0,1,2,3,4,5,6,7,8,9]
print(2*L)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
#벡터화 연산은 비교 연산과 논리 연산을 포함한
#모든 종류의 수학 연산에 대해 적용된다
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a + b)

#일반적인 리스트 객체는 다음과 같이 동작
a_L = [1,2,3]
b_L = [10,20,30]
print(2*a_L + b_L)

#비교 연산자나 논리 연산자도 다음과 같이 사용된다
print(a == 2)
print(b>10)
print((a==2) & (b>10))

[12 24 36]
[1, 2, 3, 1, 2, 3, 10, 20, 30]
[False  True False]
[False  True  True]
[False  True False]


In [10]:
#2차원 배열 만들기
#가로줄 행(횡렬 생각하자)
#세로줄 열
c = np.array([[0,1,2],[3,4,5]])
print(c)

#2차원 배열의 행과 열의 갯수는 다음처럼 구한다
print(len(c))    #행의 갯수
print(len(c[0]))    #열의 갯수

[[0 1 2]
 [3 4 5]]
2
3


In [12]:
#3차원 배열 만들기
#리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있다
#크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
d = np.array([[[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]],
            [[11,12,13,14],
             [15,16,17,18],
             [19,20,21,22]]])
#3차원 배열의 깊이, 행, 열은 다음과 같이 구할 수 있다
print(len(d), len(d[0]), len(d[0][0]))

2 3 4


In [13]:
#numpy.array에서는 ndim은 몇 차원인지,
#shape는 배열의 길이를 나타낸다. 이때 배열의 길이는 같아야 한다
a = np.array([[10,20,30,40],[50,60,70,80]])
print(a.ndim)
print(a.shape)

c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

d = np.array([[[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]],
              [[11,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]])
print(d.ndim)
print(d.shape)

2
(2, 4)
2
(2, 3)
3
(2, 3, 4)


In [14]:
#array의 값 호출
a = np.array([0,1,2,3,4])
print(a[2])

#numpy.array에서 -1은 맨 마지막 수를 의미한다
print(a[-1])

#리스트와 달리 앞에가 행, 뒤에가 열이다
a = np.array([[0,1,2],[3,4,5]])
print(a)
print(a[0,0])    #첫번째 행 첫번쩨 열
print(a[0,1])    #첫번째 행 두번째 열
print(a[-1][-1])    #마지막 행 마지막 열

2
4
[[0 1 2]
 [3 4 5]]
0
1
5


In [15]:
#배열 슬라이싱
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a)
print(a[0, :])    #첫번째 행 전체
print(a[:, 1])    #두번째 열 전체
print(a[1, 1:])    #두번째 행의 두번째 열부터 끝열까지
print(a[:2, :2])    #두번째 행까지 두번재 열까지

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [17]:
#아래와 같은 행렬 m 이 있을때 문제 해결하시오
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])
#1. 이 행렬에서 값 7을 인덱싱
print(m[1,2])
print()

#2. 이 행렬에서 값 14를 인덱싱
print(m[-1][-1])
#또는
print(m[2][4])
print()

#3. 이 행렬에서 배열 [6,7]을 슬라이싱
print(m[1,1:3])
print()

#4. 이 행렬에서 배열 [7,12] 슬라이싱
print(m[1:, 2])
print()

#5. 이 행렬에서 배열[[3,4],[8,9]]을 슬라이싱
print(m[:2, 3:])

7

14
14

[6 7]

[ 7 12]

[[3 4]
 [8 9]]


In [18]:
#배열 인덱싱
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
print(a[idx])

#조건문 연산을 사용하면 다음과 같이 간단히 쓸 수 있다
print(a%2)
print(a%2 == 0)
print(a[a%2==0])

[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [21]:
#정수 배열 인덱싱에서는 인덱스 배열의 원소 각각이
#원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수이어야 한다
#예를 들어 1차원 배열에서 홀수번재 원소만 골라내는 것은 다음과 같다
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
print(a[idx])
print()

#이때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없다.
#같은 원소를 반복해서 가리키는 경우에는
#배열 인덱스가 원래의 배열보다 더 커지기도 한다
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
print(a[idx])

[11 33 55 77 99]

[11 11 11 11 11 11 22 22 22 22 22 33 33 33 33 33]


In [22]:
x = np.array([1,2,3,4,5,6,7,8,9,10,
             11,12,13,14,15,16,17,18,19,20])
#1. 이 배열에서 3의 배수
print(x[x%3 == 0])
#2. 이 배열에서 4로 나누면 1이 남는 수
print(x[x%4 == 1])
#3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [25]:
x = np.array([1,2,3])
print(x.dtype)
x = np.array([1.0,2.0,3.0])
print(x.dtype)
x = np.array([1,2,3.0])
print(x.dtype)
print()

x = np.array([1,2,3], dtype='f')    #실수로 받는다
print(x.dtype)
print(x[0] + x[1])
x = np.array([1,2,3], dtype = 'U')    #문자로 받는다
print(x.dtype)
print(x[0] + x[1])

int64
float64
float64

float32
3.0
<U1
12


In [27]:
#inf : 무한대
#nan : 0으로 나눠서 계산 불가
print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))
print(np.log(0))
print(np.exp(-np.inf))

[  0.  inf -inf  nan]
-inf
0.0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [28]:
#크기가 정해져 있고 모든 값이 0인 배열을 생성하려면
#zeros 명령을 사용한다
#인수로는 배열 크기를 뜻하는 정수를 넣는다
a = np.zeros(5)
print(a)
print()

#크기를 뜻하는 튜플을 입력하면 다차원 배열도 만들 수 있다
b = np.zeros((2,3))
print(b)
print()

c = np.zeros((5,2), dtype='i')
print(c)
print()

d = np.zeros(5, dtype='U4')
print(d)
print()

d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
print(d)
print()

#ones를 쓰면 1로 초기화 환다
e = np.ones((2,3,4), dtype='i8')
print(e)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

['' '' '' '' '']

['abc' 'abcd' 'ABCD' '' '']

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [29]:
#크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면
#ones_like나 zeros_like 사용
f = np.ones_like(b, dtype='f')
print(f)
print()
f = np.zeros_like(b, dtype='f')
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
#배열을 초기화 하는데도 시간이 걸린다
#아무 값으로나 만들어 시간을 줄이고 싶다면
#empty 사용
g = np.empty((4,3))
print(g)

#unmpy의 range : arange
print(np.arange(3,21,2))

[[0.00000000e+000 4.65498617e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.36598737e-314]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[ 3  5  7  9 11 13 15 17 19]


In [31]:
#linspace나 logspace는 지정한 구간의 수 만큼 분할
print(np.linspace(0,100,5))    #시작, 끝(포함), 갯수
print(np.logspace(0.1, 1, 10))
print()

#2차원 배열의 전치연산은 행과 열을 바꾸는 작업
#이는 배열의 T속성으로 구할 수 있다
#메서드가 아닌 속성이라는 점에 유의
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()
print(A.T)
print()

a = np.arange(12)
print(a)
print()

b = a.reshape(3,4)    #3개의 배열로 원소 수는 4개, 이렇게 할거면 원본 배열의 숫자와 맞아야 한다
print(b)
print()

print(a.reshape(3,-1))    #3개의 배열로 원소수는 알아서(원본 배열의 숫자와 안맞아도 된다)
print()

print(a.reshape(2,2,-1))    #3차원, 2차원 2개, 1차원 개수는 알아서
print()

a = a.reshape(2,-1,2)
print(a)

[  0.  25.  50.  75. 100.]
[ 1.25892541  1.58489319  1.99526231  2.51188643  3.16227766  3.98107171
  5.01187234  6.30957344  7.94328235 10.        ]

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [32]:
#다차원 배열을 1차원 배열로 만드는 메서드
#flatten()
#ravel()
print(a)
print()
print(a.flatten())
print(a.ravel())
print()
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [33]:
#최소제곱법의 a와 b를 구하라
#a = ((x-x의 평균)*(y-y의평균)의합) / (x-x평균)^2
#b = y의 평균 - (x의 평균 * a)
x = np.array([2,4,6,8])
y = np.array([81, 93, 91, 97])
X = sum(x) / 4    #x의 평균
Y = sum(y) / 4    #y의 평균
a = sum((x-X)*(y-Y))/sum((x-X)*(x-X))
b = int(Y - (X*a))    #b니까 결과가 정수가 되게 나오게 한거지 별 의미 없을거 같다

print(a)
print(b)
print('y =',a,'x +',b)

2.3
79
y = 2.3 x + 79
