In [ ]:
#텐서플로우 코어의 프로그래밍 과정
#tensorflow module을 import하면, 이때 Default Graph가 생성됨
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.get_default_graph().get_operations()    #노드를 짜고 tensor를 구성한게 없으니까 []가 정상이다

Instructions for updating:
non-resource variables are not supported in the long term


[]

In [ ]:
a = tf.constant(7.0, name = 'data1')    #에지 : tensor
b = tf.constant(3.0, name = 'data2')    #노드(operation) : data1은 operation의 이름
c = tf.constant(2.0, name = 'data3')

tf.get_default_graph().get_operations()

[<tf.Operation 'data1' type=Const>,
 <tf.Operation 'data2' type=Const>,
 <tf.Operation 'data3' type=Const>]

In [ ]:
print(a)    #a의 값을 확인.    operation이 실행되기 전까지 텐서 a의 값이 결정되지 않은 상태

Tensor("data1:0", shape=(), dtype=float32)


In [ ]:
print(a.op)    #a에 연결된 operation을 확인.    텐서 a를 출력하는 operation에 접근

name: "data1"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 7.0
    }
  }
}



In [ ]:
print(a.op.outputs)    #a의 입력 값을 확인.    operation a의 출력에 접근하여 확인

[<tf.Tensor 'data1:0' shape=() dtype=float32>]


In [ ]:
print(a is a.op.outputs[0])    #텐서 a와 a의 operation의 출력이 같은지 확인

True


In [ ]:
print(a.op.node_def.attr['value'].tensor.float_val[0])
    #a의 operation protocol 버퍼에서 출력값을 확인해볼 수 있다

7.0


In [ ]:
#한 줄의 코드지만 텐서플로우의 연산 노드가 자동으로 추가됨
v = a * b / c

#node에 이름을 붙이지 않았으므로 default이름인 mul, truediv을 가짐
tf.get_default_graph().get_operations()

[<tf.Operation 'data1' type=Const>,
 <tf.Operation 'data2' type=Const>,
 <tf.Operation 'data3' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'truediv' type=RealDiv>]

In [ ]:
#v의 input을 찍어보면 리스트 객체의 ID가 출력됨
print('v.op.inputs = ', v.op.inputs)
tf.get_default_graph().get_operations()

v.op.inputs =  (<tf.Tensor 'mul:0' shape=() dtype=float32>, <tf.Tensor 'data3:0' shape=() dtype=float32>)


[<tf.Operation 'data1' type=Const>,
 <tf.Operation 'data2' type=Const>,
 <tf.Operation 'data3' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'truediv' type=RealDiv>]

In [ ]:
print(type(v))    #v도 tensor다

<class 'tensorflow.python.framework.ops.Tensor'>


In [ ]:
print('v.op.outputs =',v.op.outputs)    #텐서 v의 operation 출력을 확인

v.op.outputs = [<tf.Tensor 'truediv:0' shape=() dtype=float32>]


In [ ]:
print(v.op.outputs[0] is v)    #텐서 v와 v의 operation의 출력이 같은지 확인

True


In [ ]:
print(v.op)    #텐서 v의 operation의 node를 확인(v.op.node_def)

name: "truediv"
op: "RealDiv"
input: "mul"
input: "data3"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}



In [ ]:
print(v.op.inputs[0])    #텐서 v의 operation의 node input 확인
print(v.op.inputs[1])    #위에서 input으로 나온 두개(mul, data3)인지 확인

Tensor("mul:0", shape=(), dtype=float32)
Tensor("data3:0", shape=(), dtype=float32)


In [ ]:
# 1.x로 확인하는 TF 자료형
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a, b)    #a * b
e = tf.add(c, b)         #c + b
f = tf.subtract(d, e)    #d - e

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

Tensor("Const_3:0", shape=(), dtype=int32)
Tensor("Const_4:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(), dtype=int32)
Tensor("Mul_2:0", shape=(), dtype=int32)
Tensor("Add_1:0", shape=(), dtype=int32)
Tensor("Sub_1:0", shape=(), dtype=int32)


In [ ]:
#세션을 만들고 연산그래프 실행(f를 예로)
#결국, 텐서를 흘려보내면서 데이터를 처리하는 과정이 필요
#Session은 실제로 값을 대입한 그래프가 동작하도록 하는 역할을 수행
sess = tf.Session()
outs = sess.run(f)
sess.close()
print('outs =',outs)

outs = 5


In [ ]:
#문자형 constant
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#Hello, Tensorflow!라는 문자열이 들어있는 node 생성
hello = tf.constant('Hello. Tensorflow!')

#TF 세션 시작
sess = tf.Session()

#특정 노드 세션 run
print(sess.run(hello))

sess.close()

b'Hello. Tensorflow!'


In [ ]:
#실수형 constant 예제
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

node1 = tf.constant(3.0, tf.float32)    #float32 노드 생성
node2 = tf.constant(4.0)    #float32 노드 생성
node3 = tf.add(node1, node2)    #node1과 node2를 더하는 노드 생성
print('node1 :', node1, 'node2 :', node2)
print('node3 :',node3)

sess = tf.Session()
print([node1, node2])
print('sess.run(node1, node2) :', sess.run([node1, node2]))    #[3.0, 4.0]
print('sess.run(node3) :', sess.run(node3))    #7.0

sess.close()

node1 : Tensor("Const_7:0", shape=(), dtype=float32) node2 : Tensor("Const_8:0", shape=(), dtype=float32)
node3 : Tensor("Add_2:0", shape=(), dtype=float32)
[<tf.Tensor 'Const_7:0' shape=() dtype=float32>, <tf.Tensor 'Const_8:0' shape=() dtype=float32>]
sess.run(node1, node2) : [3.0, 4.0]
sess.run(node3) : 7.0


In [2]:
#플레이스 홀더
#2.x에서는 못 쓴다
#Session()안에서 값이 안 바뀐다
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y, feed_dict = {x:input_data})#placeholder는 feed_dict={} 꼭 써야된다
sess.close()

print(result)

[ 2.  4.  6.  8. 10.]


In [4]:
#placeholder의 다른 형태
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

p_holder1 = tf.placeholder(dtype=tf.float32)
p_holder2 = tf.placeholder(dtype=tf.float32)
p_holder3 = tf.placeholder(dtype=tf.float32)
val1 = 5
val2 = 10
val3 = 3
ret_val = p_holder1 * p_holder2 + p_holder3

sess = tf.Session()
feed_dict_data = {p_holder1:val1, p_holder2:val2, p_holder3:val3}
result = sess.run(ret_val, feed_dict=feed_dict_data)
sess.close()

print(result)

53.0


In [5]:
#placeholder 마지막 예제
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

I = tf.placeholder(tf.float32, [2,4])
i = [[1,2,3,4],[5,6,7,8]]

W = tf.placeholder(tf.float32, [4,2])
w = [[1,1],[2,2],[3,3],[4,4]]

#input 데이터와 Weight를 행렬곱 수행
m_cal = tf.matmul(I,W)

sess = tf.Session()
print(sess.run(m_cal, feed_dict={I:i, W:w}))
sess.close()

[[30. 30.]
 [70. 70.]]


In [6]:
#variable 초기화
#Session()안에서 값이 바뀔 수 있다
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

I = tf.Variable([[1,2,3,4],[5,6,7,8]],dtype=tf.float32)
W = tf.Variable([[1,1],[2,2],[3,3],[4,4]],dtype=tf.float32)

#input 데이터와 Weight를 행렬곱 수행
m_cal = tf.matmul(I, W)

sess = tf.Session()
sess.run(tf.global_variables_initializer())#variable은 이거 꼭 써야된다
print(sess.run(m_cal))
sess.close()

[[30. 30.]
 [70. 70.]]


In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W=tf.Variable([2],dtype=tf.float32)
y = W * x

sess = tf.Session()
sess.run(tf.global_variables_initializer())#global없으면 variable은 에러난다
result = sess.run(y, feed_dict={x:input_data})
print(result)
sess.close()


[ 2.  4.  6.  8. 10.]


In [8]:
#variable 재할당
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#변수를 재할당하는 방법(스칼라의 경우)
x = tf.Variable(5, dtype=tf.int32)
print(x)

z = tf.assign(x,7)#x를 7이라는 값으로 바꿔줌
#tf.global_variables_initializer()
                       #x가 assign이 되지 않으면 반드시
                       #global_variables_initializer()를 해주어야 하지만 변수 x에 값이 assgin 되었으므로
                       #global_variables_initializer()해주지 않아도 에러가 나지 않음

sess = tf.Session()
sess.run(z)
y = sess.run(x)
print(y)
sess.close()

<tf.Variable 'Variable_3:0' shape=() dtype=int32_ref>
7


In [9]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

#변수를 재할당하는 방법(2차원 텐서(행렬)의 경우)
x = tf.Variable(tf.zeros((2,2)),dtype=tf.float32)
print(x)

y = tf.Variable([[1,2],[3,4]],dtype=tf.float32)
x = tf.assign(x,y)
sess = tf.Session()
z = tf.global_variables_initializer()    #x는 assign되어있지만, y는 assign되어있지 않으므로 
                                         #global_variables_initializer()를 해주어야 함
sess.run(z)
k = sess.run(x)
sess.close()

print(k)

<tf.Variable 'Variable_4:0' shape=(2, 2) dtype=float32_ref>
[[1. 2.]
 [3. 4.]]


In [13]:
#코드 완성하기
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

mat_img = [1,2,3,4,5]
label = [10,20,30,40,50]
ph_img = tf.placeholder(dtype=tf.float32)
ph_lb = tf.placeholder(dtype=tf.float32)

ret_tensor = ph_img + ph_lb
#==========여기서부터
sess = tf.Session()
result=sess.run(ret_tensor,feed_dict={ph_img:mat_img, ph_lb:label})
sess.close()

print(result)

[11. 22. 33. 44. 55.]


In [14]:
#텐서플로우 행렬 사용하기
#constant 및 variable 뿐 아니라, placeholder에도 행렬로 저장이 가능하다
#다음은 placeholder에 행렬 데이터를 feeding해주는 예제다
#입력 데이터 행렬 x는 placeholder 타입으로 3x3행렬이고,
#여기에 곱하는 값 w는 1x3 행렬이다
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data =  [ [1., 2., 3.], [1., 2., 3.], [2., 3., 4.]]#3X3 matrix
x = tf.placeholder(dtype=tf.float32, shape=[None,3])#들어오는 숫자를 정해두지 않고 non으로 해두면 행렬을 다 받을 수 있다
w = tf.Variable([[2.],[2.],[2.]], dtype=tf.float32) #3X1 matrix
y = tf.matmul(x,w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x:input_data})
sess.close()
print(result)

[[12.]
 [12.]
 [18.]]


In [15]:
#브로드 캐스팅
#텐서플로우 그리고 파이썬으로 행렬 프로그래밍을 하다보면 헷갈리는 개념으로
#브로드 캐스팅이라는게 있다
#브로드 캐스팅이란 행렬연산에서 차원이 맞지 않을 때 행렬을 자동으로 늘려줘서
#차원을 맞춰주는 개념으로 늘리는 것은 가능하지만 줄이는 것은 불가능하다
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

input_data = [[1,1,1], [2,2,2]]
x = tf.placeholder(dtype=tf.float32, shape=[2,3])
w = tf.Variable([[2],[2],[2]], dtype=tf.float32)
b = tf.Variable([4], dtype=tf.float32)
y = tf.matmul(x,w) + b  #x,w,b의 행렬의 차원이 다른데 계산이 된다
print(x.get_shape())

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x:input_data})
sess.close()

print(result)

(2, 3)
[[10.]
 [16.]]


In [16]:
#텐서플로우 행렬 사용하기
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.constant([[1.0, 2.0, 3.0]])
w = tf.constant([[2.0], [2.0], [2.0]])
y = tf.matmul(x, w)
print(x.get_shape())
print(w.get_shape())
print(y.get_shape())
print(y)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)
sess.close()

print(result)

(1, 3)
(3, 1)
(1, 1)
Tensor("MatMul_4:0", shape=(1, 1), dtype=float32)
[[12.]]
