In [1]:
#배열의 크기 변형
import numpy as np
a = np.arange(12)
print(a)
b = a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
#하나는 -1을 쓸 수 있는데, 그럼 칸을 알아서 맞춰준다
print(a.reshape(3, -1))
print(a.reshape(2,2,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [3]:
#다차원 배열을 무조건 1차원으로 펼치기 위해서는 flatten이나 ravel
print(a.flatten())
print(a.reshape(2,2,-1))
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
#numpy 배열 복제
#numpy배열은 list, tuple과 동일하게 복사하여 변경할 경우, 원본의 값도 변경된다
#numpy배열.copy()를 통하여 복제할 경우, 원본과 별개의 배열이 생성된다
import numpy as np
a = np.array([1,2,3,4,5])
b = a
c = a.copy()
b[0] = 99
print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [6]:
#배열과 리스트의 벡터연산
import numpy as np
a = [1,2,3,4,5]
b = np.array(a)
c = np.array([1,3,5])
print(a*2)
print(b*2)
print(c+3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [7]:
#다차원 배열
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a)
print(b)
print(a[0][1])
print(b[0][1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
2
4


In [8]:
#모든 값이 1인 배열 ones_like
#모든 값이 0인 배열 zeros_like
import numpy as np
a = np.ones((2,2), dtype=int)
b = [1,2,3,4,5]
c = np.ones_like(b, dtype=int)    #배열의 크기는 b와 동일하며, 그 내용은 1로 채운다
print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 1 1 1 1]


In [9]:
#모든 값이 비어있는 배열
import numpy as np
a = np.empty((2,2), dtype=int)
b = [1,2,3,4,5]
c = np.empty_like(b, dtype=int)
print(a)
print(b)
print(c)

[[4607182418800017408 4607182418800017408]
 [4607182418800017408                   0]]
[1, 2, 3, 4, 5]
[99  2  3  4  5]


In [10]:
#대각의 값이 1인 배열(단위행렬)
a = np.identity(4, dtype=int)
b = np.eye(4, 4, k=1, dtype=int)    #k가 음수면 왼쪽 아래방향을 간다
print(a)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
