In [1]:
#과적합 피하기
import pandas as pd
df = pd.read_csv("/sonar.csv", header=None)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

초음파로 광물 예측하기 코드 작성(이항분류)
- sonar.csv 파일을 사용하여 광물 예측하는 학습
- Class가 문자열이므로 변환 필요

In [2]:
#이항분류
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder    #자연어처리를 위해 사이킷런 다운

import pandas as pd
#import seaborn as sns    #이 두줄은 그래프를 위한 선언
#import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv("/sonar.csv", delimiter = ",")

#데이터 분류
dataset = df.values
X = dataset[:, :60].astype(float)    #속성
Y_obj = dataset[:, 60]    #클래스

#문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
#Y_encoded = tf.keras.utils.to_categorical(Y)   #이건 다항분류를 위해 있는듯

#모델의 설정
model = Sequential()
model.add(Dense(120, input_dim=60, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#모델 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#모델 실행
model.fit(X, Y, epochs = 30, batch_size = 10)

#결과 출력
ans = model.evaluate(X, Y)
print("\n Accuracy : %.2f%%" % (ans[1]*100))

Epoch 1/30
21/21 [==============================] - 1s 2ms/step - loss: 0.6701 - accuracy: 0.6280
Epoch 2/30
21/21 [==============================] - 0s 2ms/step - loss: 0.6183 - accuracy: 0.6957
Epoch 3/30
21/21 [==============================] - 0s 2ms/step - loss: 0.5258 - accuracy: 0.7633
Epoch 4/30
21/21 [==============================] - 0s 2ms/step - loss: 0.4510 - accuracy: 0.8164
Epoch 5/30
21/21 [==============================] - 0s 2ms/step - loss: 0.4513 - accuracy: 0.7585
Epoch 6/30
21/21 [==============================] - 0s 3ms/step - loss: 0.4121 - accuracy: 0.7778
Epoch 7/30
21/21 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8213
Epoch 8/30
21/21 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8696
Epoch 9/30
21/21 [==============================] - 0s 2ms/step - loss: 0.3238 - accuracy: 0.8744
Epoch 10/30
21/21 [==============================] - 0s 2ms/step - loss: 0.2742 - accuracy: 0.8841
Epoch 11/30
21/21 [

과적합 이해하기  
과적합이란  
모델이 학습 데이터셋 안에서는 일정 수준 이상의 예측 정확도를 보이지만,  
새로운 데이터에 적용하면 잘 맞지 않는 것을 말함  

학습셋과 테스트셋  
test_size : 테스트 셋 구성의 비율. train_size의  옵션과 반대 관계에 있는 옵션 값이며,  
주로 test_size를 지정해 줌. 0.2는 전체 데이터 셋의   20%를 test셋으로 지정하겠다는 의미.  
default값은 0.25  
shuffle : default=True.split을 해주기 이전에 섞을 건지 여부  
random_state : 세트를 섞을 때 해당 int 값을 보고 섞으며, 하이퍼 파라미터를 튜닝시  
이 값을 고정해두고 튜닝해야 매번 데이터셋이 변경되는 것을 방지할 수 있음

In [3]:
from sklearn.model_selection import train_test_split

#학습셋과 테스트셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)
print(X)
print(Y)

[[0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.01   0.0171 0.0623 ... 0.0044 0.004  0.0117]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [5]:
#광물 구분하기 학습셋과 테스트셋으로 구하기
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder    #자연어처리를 위해 사이킷런 다운
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv("/sonar.csv", header=None)

#데이터 분류
dataset = df.values
X = dataset[:, :60].astype(float)    #속성
Y_obj = dataset[:, 60]    #클래스

#문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

#학습셋과 테스트셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

#모델의 설정
model = Sequential()
model.add(Dense(120, input_dim=60, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#모델 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#모델 실행
model.fit(X_train, Y_train, epochs = 30, batch_size = 10)

#결과 출력
#학습셋으로 모델 검증
print("\n Train Accuracy : %.2f%%" % (model.evaluate(X_train, Y_train)[1]*100))
#테스트셋에 모델 적용
print("\n Test Accuracy : %.2f%%" % (model.evaluate(X_test,Y_test)[1]*100))

Epoch 1/30
15/15 [==============================] - 0s 2ms/step - loss: 0.6650 - accuracy: 0.6483
Epoch 2/30
15/15 [==============================] - 0s 2ms/step - loss: 0.6114 - accuracy: 0.7724
Epoch 3/30
15/15 [==============================] - 0s 2ms/step - loss: 0.5641 - accuracy: 0.7034
Epoch 4/30
15/15 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.7724
Epoch 5/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4906 - accuracy: 0.7655
Epoch 6/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4631 - accuracy: 0.7931
Epoch 7/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4415 - accuracy: 0.8345
Epoch 8/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4422 - accuracy: 0.7862
Epoch 9/30
15/15 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 0.8828
Epoch 10/30
15/15 [==============================] - 0s 2ms/step - loss: 0.3770 - accuracy: 0.8207
Epoch 11/30
15/15 [

iris.csv를 사용해서 학습셋 검증셋으로 구분해보기  
- 아이리스 학습을 통해 두 데이터셋간의 차이를 확인해보기
- 비교를 위해 batch_size는 사용하지 않음  


아이리스는 데이터 자체가 겹치는게 많이 없어서 과적합이 잘 생기지 않는다

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder    #자연어처리를 위해 사이킷런 다운
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv("/iris.csv", header=None)

#데이터 분류
dataset = df.values
X = dataset[:, 0:4].astype(float)    #속성
Y_obj = dataset[:, 4]    #클래스

#문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
Y_encoded = tf.keras.utils.to_categorical(Y)

#학습셋과 테스트셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_encoded, test_size=0.3, random_state=seed)

#모델의 설정
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

#모델 컴파일
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#모델 실행
model.fit(X_train, Y_train, epochs = 100)

#결과 출력
#학습셋으로 모델 검증
print("\n Train Accuracy : %.2f%%" % (model.evaluate(X_train, Y_train)[1]*100))
#테스트셋에 모델 적용
print("\n Test Accuracy : %.2f%%" % (model.evaluate(X_test,Y_test)[1]*100))

Epoch 1/100
4/4 [==============================] - 0s 3ms/step - loss: 2.4204 - accuracy: 0.3714
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 2.3159 - accuracy: 0.3714
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 2.2013 - accuracy: 0.3714
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 2.0975 - accuracy: 0.3714
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 1.9940 - accuracy: 0.3714
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 1.8782 - accuracy: 0.3714
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 1.7714 - accuracy: 0.3810
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 1.6646 - accuracy: 0.3810
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 1.5576 - accuracy: 0.4286
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 1.4488 - accuracy: 0.5143
Epoch 11/100
4/4 [===========

모델 저장과 재사용  
가중치와 바이어스들에 대한 정보를 저장하여 앞으로는 금방 계산할 수 있게 함

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder    #자연어처리를 위해 사이킷런 다운
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv("/sonar.csv", header=None)

#데이터 분류
dataset = df.values
X = dataset[:, :60].astype(float)    #속성
Y_obj = dataset[:, 60]    #클래스

#문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

#학습셋과 테스트셋의 구분
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

#모델의 설정
model = Sequential()
model.add(Dense(120, input_dim=60, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#모델 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#모델 실행
model.fit(X_train, Y_train, epochs = 30, batch_size = 10)

#광물 구분하기 학습셋과 테스트셋으로 구하기에서 추가 코드
from tensorflow.keras.models import load_model
model.save('my_model.h5')   #모델을 컴퓨터에 저장
del model    #테스트를 위해 메모리 내의 모델을 삭제
model = load_model('my_model.h5')    #모델을 새로 불러옴

#결과 출력
#테스트셋에 모델 적용
print("\n Test Accuracy : %.2f%%" % (model.evaluate(X_test,Y_test)[1]*100))

Epoch 1/30
15/15 [==============================] - 0s 2ms/step - loss: 0.6650 - accuracy: 0.6483
Epoch 2/30
15/15 [==============================] - 0s 2ms/step - loss: 0.6114 - accuracy: 0.7724
Epoch 3/30
15/15 [==============================] - 0s 2ms/step - loss: 0.5641 - accuracy: 0.7034
Epoch 4/30
15/15 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.7724
Epoch 5/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4906 - accuracy: 0.7655
Epoch 6/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4631 - accuracy: 0.7931
Epoch 7/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4415 - accuracy: 0.8345
Epoch 8/30
15/15 [==============================] - 0s 2ms/step - loss: 0.4422 - accuracy: 0.7862
Epoch 9/30
15/15 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 0.8828
Epoch 10/30
15/15 [==============================] - 0s 2ms/step - loss: 0.3770 - accuracy: 0.8207
Epoch 11/30
15/15 [

k겹 교차 검증  
데이터가 많지 않을때 사용  
여러번 학습하고 여러번 검증  
사이킷런 사용  

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder    #자연어처리를 위해 사이킷런 다운
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

import pandas as pd
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

#데이터 입력
df = pd.read_csv("/sonar.csv", header=None)

#데이터 분류
dataset = df.values
X = dataset[:, 0:60]    #상속
#X = dataset[:, :60].astype(float)    #이렇게 쓸 경우 fit 하기전 converter를 안해도 됨
Y_obj = dataset[:, 60]    #클래스

#문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

#10개의 파일로 쪼갬
n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

#빈 accuracy 배열
accuracy = []

#모델의 설정, 컴파일, 실행
for train, test in skf.split(X,Y):
    #모델의 설정
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    #모델 컴파일
    model.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])

    #X = dataset[:, :60].astype(float) 쓰면 아래 두줄 생략 가능
    X_train = tf.convert_to_tensor(X[train], dtype=tf.float32)
    Y_train = tf.convert_to_tensor(Y[train], dtype=tf.float32)
    
    #모델 실행
    model.fit(X_train, Y_train, epochs = 100, batch_size = 5)
    
    X_test = tf.convert_to_tensor(X[test], dtype=tf.float32)
    Y_test = tf.convert_to_tensor(Y[test], dtype=tf.float32)
    k_accuracy = "%.4f" %(model.evaluate(X_test, Y_test)[1])
    accuracy.append(k_accuracy)
    
#결과 출력
print("\n %.f flod accuracy :" %n_fold, accuracy)

Epoch 1/100
38/38 [==============================] - 0s 1ms/step - loss: 0.2426 - accuracy: 0.5455
Epoch 2/100
38/38 [==============================] - 0s 1ms/step - loss: 0.2260 - accuracy: 0.6578
Epoch 3/100
38/38 [==============================] - 0s 1ms/step - loss: 0.2156 - accuracy: 0.7326
Epoch 4/100
38/38 [==============================] - 0s 1ms/step - loss: 0.2057 - accuracy: 0.7487
Epoch 5/100
38/38 [==============================] - 0s 1ms/step - loss: 0.1946 - accuracy: 0.7219
Epoch 6/100
38/38 [==============================] - 0s 2ms/step - loss: 0.1843 - accuracy: 0.7540
Epoch 7/100
38/38 [==============================] - 0s 1ms/step - loss: 0.1730 - accuracy: 0.7861
Epoch 8/100
38/38 [==============================] - 0s 1ms/step - loss: 0.1631 - accuracy: 0.8075
Epoch 9/100
38/38 [==============================] - 0s 2ms/step - loss: 0.1559 - accuracy: 0.8075
Epoch 10/100
38/38 [==============================] - 0s 1ms/step - loss: 0.1504 - accuracy: 0.8075
Epoch 11/

베스트 모델 만들기

In [13]:
df_pre = pd.read_csv("/wine.csv", header=None)
df = df_pre.sample(frac=1)
#sample()함수는 원본 데이터에서 정해진 비율만큼 랜덤으로 뽑아오는 함수
#frac=1이라고 지정하면 원본 데이터의 100%를 불러오라는 의미
#frac=0.5라고 지정하면 50%만 랜덤으로 불러옴
print(df.head(5))    #100%불러왔으니까 그중 처음 5줄 출력

       0     1     2     3      4     5   ...       7     8     9     10  11  12
5316  6.3  0.18  0.24   3.4  0.053  20.0  ...  0.99373  3.11  0.52   9.2   6   0
5210  6.8  0.14  0.18   1.4  0.047  30.0  ...  0.99164  3.27  0.54  11.2   6   0
3518  7.3  0.22  0.50  13.7  0.049  56.0  ...  0.99940  3.24  0.66   9.0   6   0
1622  7.6  0.67  0.14   1.5  0.074  25.0  ...  0.99370  3.05  0.51   9.3   5   0
2443  7.3  0.21  0.29   1.6  0.034  29.0  ...  0.99170  3.30  0.50  11.0   8   0

[5 rows x 13 columns]


In [14]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 5316 to 2732
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       6497 non-null   float64
 1   1       6497 non-null   float64
 2   2       6497 non-null   float64
 3   3       6497 non-null   float64
 4   4       6497 non-null   float64
 5   5       6497 non-null   float64
 6   6       6497 non-null   float64
 7   7       6497 non-null   float64
 8   8       6497 non-null   float64
 9   9       6497 non-null   float64
 10  10      6497 non-null   float64
 11  11      6497 non-null   int64  
 12  12      6497 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 710.6 KB
None
